# Generated by Django 4.1.7 on 2023-02-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captionapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="caption",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
