# Generated by Django 4.1.7 on 2023-02-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("captionapp", "0003_alter_image_caption"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="created_at",
            new_name="uploaded_at",
        ),
    ]
