# Generated by Django 4.1.7 on 2023-02-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("captionapp", "0004_rename_created_at_image_uploaded_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="caption",
            new_name="feedback",
        ),
    ]
