# Generated by Django 4.1.7 on 2023-02-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("captionapp", "0005_rename_caption_image_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="uploaded_at",
        ),
    ]
